server:
  service:
    type: NodePort
    nodePorts:
      http: "32002"
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
  persistence:
    enabled: true
    size: 10Gi

alertmanager:
  enabled: true
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  persistence:
    enabled: true
    size: 2Gi