apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
  labels:
    app: smtp4dev
spec:
  type: {{ .Values.service.type }}
  selector:
    app: smtp4dev
  ports:
    - name: smtp
      protocol: TCP
      port: {{ .Values.service.smtpPort }}
      targetPort: 25
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80 