---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storageclass-gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp3