apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
    
    jobs:
      - script: |
          freestyleJob('hello-world') {
            description('A simple Hello World freestyle job')
            steps {
              shell('echo "Hello World!"')
            }
          } 