apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-config
  namespace: monitoring
  labels:
    app: grafana
data:
  contact-points.yaml: |
    apiVersion: 1
    contactPoints:
      - name: email-contact-point
        receivers:
          - uid: email-receiver
            type: email
            settings:
              addresses: "ashymanouski@student.com"
            disableResolveMessage: false
        disableProvenance: false

  notification-policies.yaml: |
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: email-contact-point
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h

  alert-rules.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: kubernetes-cluster-alerts
        folder: dashboards
        interval: 1m
        rules:
          - uid: high-cpu-utilization
            title: High CPU Utilization
            condition: B
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus-uid
                model:
                  editorMode: code
                  expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
              - refId: B
                queryType: ""
                relativeTimeRange:
                  from: 0
                  to: 0
                datasourceUid: __expr__
                model:
                  type: threshold
                  expression: A
                  conditions:
                    - evaluator:
                        params: [80]
                        type: gt
                      operator:
                        type: and
                      query:
                        params: [A]
                      reducer:
                        params: []
                        type: last
                      type: query
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: B
            noDataState: NoData
            execErrState: Alerting
            for: 5m
            annotations:
              summary: High CPU utilization detected
              description: CPU utilization is above 80% for more than 5 minutes on node {{ $labels.instance }}
            labels:
              severity: warning
            isPaused: false

          - uid: high-memory-utilization
            title: High Memory Utilization
            condition: B
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus-uid
                model:
                  editorMode: code
                  expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
              - refId: B
                queryType: ""
                relativeTimeRange:
                  from: 0
                  to: 0
                datasourceUid: __expr__
                model:
                  type: threshold
                  expression: A
                  conditions:
                    - evaluator:
                        params: [85]
                        type: gt
                      operator:
                        type: and
                      query:
                        params: [A]
                      reducer:
                        params: []
                        type: last
                      type: query
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: B
            noDataState: NoData
            execErrState: Alerting
            for: 5m
            annotations:
              summary: High memory utilization detected
              description: Memory utilization is above 85% for more than 5 minutes on node {{ $labels.instance }}
            labels:
              severity: warning
            isPaused: false 