admin:
  user: "admin"
  password: ""
  existingSecret: ""

service:
  type: NodePort
  ports:
    grafana: 3000
  nodePorts:
    grafana: "32003"

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

persistence:
  enabled: true
  size: 8Gi

datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true

# dashboardsProvider:
#   enabled: true

# dashboardsConfigMaps:
#   - configMapName: kubernetes-cluster-dashboard
#     fileName: kubernetes-cluster.json
#   - configMapName: node-exporter-dashboard
#     fileName: node-exporter.json 