apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
data:
  admin-user: {{ .Values.grafana.admin.user | b64enc }}
  admin-password: {{ .Values.grafana.admin.password | b64enc }} 