name: Deploy Jenkins

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
        
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
        
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=./kubeconfig
        
    - name: Deploy Jenkins
      run: |
        export KUBECONFIG=./kubeconfig
        
        # Create namespace
        kubectl create namespace jenkins --dry-run=client -o yaml | kubectl apply -f -
        
        # Apply volume
        kubectl apply -f manifests/jenkins-01-volume.yaml
        
        # Apply permissions fix
        kubectl apply -f manifests/fix-permissions-pod.yaml
        
        # Wait for permissions fix to complete
        echo "Waiting for permissions fix to complete..."
        kubectl wait --for=condition=ready pod/jenkins-permissions-fix -n jenkins --timeout=300s
        
        # Check logs
        kubectl logs jenkins-permissions-fix -n jenkins
        
        # Delete permissions fix pod
        kubectl delete pod jenkins-permissions-fix -n jenkins
        
        # Apply service account
        kubectl apply -f manifests/jenkins-02-sa.yaml
        
        # Install Jenkins with Helm
        helm repo add jenkinsci https://charts.jenkins.io
        helm repo update
        
        helm upgrade --install jenkins jenkinsci/jenkins \
          --namespace jenkins \
          --values manifests/jenkins-values.yaml \
          --wait \
          --timeout=10m
          
    - name: Verify deployment
      run: |
        export KUBECONFIG=./kubeconfig
        
        # Wait for Jenkins to be ready
        kubectl wait --for=condition=ready pod/jenkins-0 -n jenkins --timeout=600s
        
        # Get Jenkins status
        kubectl get pods -n jenkins
        kubectl get svc -n jenkins
        
        echo "Jenkins deployment completed successfully!"