name: Terraform

on:
  push:
    branches:
      - main
      - task_1
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform/task-1

  terraform-plan:
    name: Terraform Plan
    needs: terraform-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_EDU_ACCOUNT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_EDU_ACCOUNT_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/task-1

      - name: Terraform Plan
        run: terraform plan -var-file="env/main.tfvars"
        working-directory: terraform/task-1

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_EDU_ACCOUNT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_EDU_ACCOUNT_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/task-1

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="env/main.tfvars"
        working-directory: terraform/task-1